version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: supportdesk-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: supportdesk-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/supportdesk
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - mongo
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: supportdesk-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  mongo-data: 